import { Account, Budget, CurrencyConfig, RecurringRule, SavingsGoal, SmartNotification, Subscription, Transaction, UserSettings } from '../types';

export const SUPPORTED_CURRENCIES: CurrencyConfig[] = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', exchangeRateToINR: 1 },
  { code: 'USD', symbol: '$', name: 'US Dollar', exchangeRateToINR: 86.5 },
  { code: 'EUR', symbol: '€', name: 'Euro', exchangeRateToINR: 92.4 },
  { code: 'GBP', symbol: '£', name: 'British Pound', exchangeRateToINR: 109.8 },
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham', exchangeRateToINR: 23.5 },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar', exchangeRateToINR: 62.1 },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', exchangeRateToINR: 56.4 },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', exchangeRateToINR: 64.8 },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', exchangeRateToINR: 0.58 },
];

export const EXPENSE_CATEGORIES = [
  { name: 'Food & Dining', icon: 'Utensils', color: '#F59E0B', subcategories: ['Groceries', 'Restaurants', 'Food Delivery', 'Coffee & Snacks'] },
  { name: 'Transport', icon: 'Car', color: '#3B82F6', subcategories: ['Fuel', 'Cab & Rideshare', 'Public Transit', 'Maintenance'] },
  { name: 'Shopping', icon: 'ShoppingBag', color: '#EC4899', subcategories: ['Clothing', 'Electronics', 'Home & Decor', 'Gifts'] },
  { name: 'Bills & Utilities', icon: 'Zap', color: '#EAB308', subcategories: ['Electricity', 'Water', 'Mobile', 'Broadband', 'LPG Gas'] },
  { name: 'Health', icon: 'HeartPulse', color: '#10B981', subcategories: ['Medicines', 'Doctor Consult', 'Diagnostics', 'Insurance'] },
  { name: 'Education', icon: 'GraduationCap', color: '#8B5CF6', subcategories: ['Courses', 'Books', 'Certifications', 'Tuition'] },
  { name: 'Entertainment', icon: 'Film', color: '#6366F1', subcategories: ['Movies', 'Gaming', 'Events', 'Streaming'] },
  { name: 'Personal Care', icon: 'Sparkles', color: '#14B8A6', subcategories: ['Salon', 'Cosmetics', 'Wellness', 'Spa'] },
  { name: 'Rent & Housing', icon: 'Home', color: '#64748B', subcategories: ['Apartment Rent', 'Society Maintenance', 'Repairs'] },
  { name: 'Travel', icon: 'Plane', color: '#06B6D4', subcategories: ['Flights', 'Hotels', 'Sightseeing', 'Transit'] },
  { name: 'Investments', icon: 'TrendingUp', color: '#D4AF37', subcategories: ['Mutual Funds', 'Stocks', 'Gold', 'Fixed Deposit'] },
  { name: 'Miscellaneous', icon: 'MoreHorizontal', color: '#94A3B8', subcategories: ['Other', 'Charity', 'Fines'] },
];

export const INCOME_CATEGORIES = [
  { name: 'Salary', icon: 'Briefcase', color: '#10B981' },
  { name: 'Freelance & Consulting', icon: 'Laptop', color: '#3B82F6' },
  { name: 'Business Revenue', icon: 'Store', color: '#8B5CF6' },
  { name: 'Investment Returns', icon: 'TrendingUp', color: '#D4AF37' },
  { name: 'Rental Income', icon: 'Home', color: '#F59E0B' },
  { name: 'Refunds & Cashback', icon: 'RotateCcw', color: '#06B6D4' },
  { name: 'Gifts & Grants', icon: 'Gift', color: '#EC4899' },
  { name: 'Other Income', icon: 'PlusCircle', color: '#64748B' },
];

export const INITIAL_USER_SETTINGS: UserSettings = {
  id: 'user-default-1',
  baseCurrency: 'INR',
  pinCode: '',
  isAppLocked: true,
  requirePinOnResume: true,
  biometricSimulated: true,
  theme: 'royal_dark',
  userName: 'User',
  isOnboarded: false,
  emergencyFundMonthsTarget: 6,
  lastCloudSync: new Date().toISOString(),
};

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-hdfc-salary',
    name: 'Primary Bank Account',
    type: 'bank',
    institution: 'Bank',
    currency: 'INR',
    openingBalance: 0,
    currentBalance: 0,
    includeInNetWorth: true,
    isArchived: false,
    color: '#001F54',
    iconName: 'Landmark',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-icici-savings',
    name: 'Savings Account',
    type: 'bank',
    institution: 'Bank',
    currency: 'INR',
    openingBalance: 0,
    currentBalance: 0,
    includeInNetWorth: true,
    isArchived: false,
    color: '#034078',
    iconName: 'Building2',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-cash-wallet',
    name: 'Physical Cash Wallet',
    type: 'cash',
    institution: 'Cash Wallet',
    currency: 'INR',
    openingBalance: 0,
    currentBalance: 0,
    includeInNetWorth: true,
    isArchived: false,
    color: '#10B981',
    iconName: 'Banknote',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-regalia-card',
    name: 'Credit Card',
    type: 'credit_card',
    institution: 'Card Provider',
    currency: 'INR',
    openingBalance: 0,
    currentBalance: 0,
    creditLimit: 100000,
    billingCycleDay: 18,
    paymentDueDay: 7,
    includeInNetWorth: true,
    isArchived: false,
    color: '#D4AF37',
    iconName: 'CreditCard',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-upi-wallet',
    name: 'UPI Wallet',
    type: 'upi_wallet',
    institution: 'UPI FastPay',
    currency: 'INR',
    openingBalance: 0,
    currentBalance: 0,
    includeInNetWorth: true,
    isArchived: false,
    color: '#1282A2',
    iconName: 'Smartphone',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEMO_ACCOUNTS: Account[] = [
  {
    id: 'acc-hdfc-salary',
    name: 'HDFC Salary Account',
    type: 'bank',
    institution: 'HDFC Bank',
    currency: 'INR',
    openingBalance: 45000,
    currentBalance: 78400,
    includeInNetWorth: true,
    isArchived: false,
    color: '#001F54',
    iconName: 'Landmark',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-icici-savings',
    name: 'ICICI Wealth Savings',
    type: 'bank',
    institution: 'ICICI Bank',
    currency: 'INR',
    openingBalance: 30000,
    currentBalance: 42500,
    includeInNetWorth: true,
    isArchived: false,
    color: '#034078',
    iconName: 'Building2',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-cash-wallet',
    name: 'Physical Cash Wallet',
    type: 'cash',
    institution: 'Cash Wallet',
    currency: 'INR',
    openingBalance: 5000,
    currentBalance: 3850,
    includeInNetWorth: true,
    isArchived: false,
    color: '#10B981',
    iconName: 'Banknote',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-regalia-card',
    name: 'Regalia Gold Card',
    type: 'credit_card',
    institution: 'HDFC Bank',
    currency: 'INR',
    openingBalance: 0,
    currentBalance: 16800,
    creditLimit: 300000,
    billingCycleDay: 18,
    paymentDueDay: 7,
    includeInNetWorth: true,
    isArchived: false,
    color: '#D4AF37',
    iconName: 'CreditCard',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-upi-wallet',
    name: 'Paytm & UPI Wallet',
    type: 'upi_wallet',
    institution: 'UPI FastPay',
    currency: 'INR',
    openingBalance: 2000,
    currentBalance: 2450,
    includeInNetWorth: true,
    isArchived: false,
    color: '#1282A2',
    iconName: 'Smartphone',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  {
    id: 'b-food',
    name: 'Food & Dining',
    type: 'monthly',
    amount: 5000,
    spent: 0,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Food & Dining',
    alertThreshold: 80,
    carryForward: false,
  },
  {
    id: 'b-shopping',
    name: 'Shopping & Apparel',
    type: 'monthly',
    amount: 3000,
    spent: 0,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Shopping',
    alertThreshold: 90,
    carryForward: true,
  },
  {
    id: 'b-transport',
    name: 'Transport & Commute',
    type: 'monthly',
    amount: 4000,
    spent: 0,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Transport',
    alertThreshold: 85,
    carryForward: false,
  },
  {
    id: 'b-entertainment',
    name: 'Entertainment & Outings',
    type: 'monthly',
    amount: 2500,
    spent: 0,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Entertainment',
    alertThreshold: 80,
    carryForward: false,
  },
  {
    id: 'b-utilities',
    name: 'Bills & Utilities',
    type: 'monthly',
    amount: 6000,
    spent: 0,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Bills & Utilities',
    alertThreshold: 90,
    carryForward: false,
  },
  {
    id: 'b-trip-goa',
    name: 'Goa Weekend Getaway',
    type: 'custom',
    amount: 25000,
    spent: 0,
    startDate: '2026-09-10',
    endDate: '2026-09-25',
    category: 'Travel',
    alertThreshold: 80,
    carryForward: false,
  },
];

export const DEMO_BUDGETS: Budget[] = [
  {
    id: 'b-food',
    name: 'Food & Dining',
    type: 'monthly',
    amount: 5000,
    spent: 3200,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Food & Dining',
    alertThreshold: 80,
    carryForward: false,
    aiSuggestions: 'Food delivery is pacing 24% higher than last week. Consider home meals for the remaining 8 days.',
  },
  {
    id: 'b-shopping',
    name: 'Shopping & Apparel',
    type: 'monthly',
    amount: 3000,
    spent: 4500,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Shopping',
    alertThreshold: 90,
    carryForward: true,
    aiSuggestions: 'Exceeded planned limit by ₹1,500 due to festive purchase. Consider reallocating from flexible spending.',
  },
  {
    id: 'b-transport',
    name: 'Transport & Commute',
    type: 'monthly',
    amount: 4000,
    spent: 2200,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Transport',
    alertThreshold: 85,
    carryForward: false,
  },
  {
    id: 'b-entertainment',
    name: 'Entertainment & Outings',
    type: 'monthly',
    amount: 2500,
    spent: 1400,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Entertainment',
    alertThreshold: 80,
    carryForward: false,
  },
  {
    id: 'b-utilities',
    name: 'Bills & Utilities',
    type: 'monthly',
    amount: 6000,
    spent: 4800,
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    category: 'Bills & Utilities',
    alertThreshold: 90,
    carryForward: false,
  },
  {
    id: 'b-trip-goa',
    name: 'Goa Weekend Getaway',
    type: 'custom',
    amount: 25000,
    spent: 18400,
    startDate: '2026-09-10',
    endDate: '2026-09-25',
    category: 'Travel',
    alertThreshold: 80,
    carryForward: false,
    aiSuggestions: 'Hotel booked under budget; remaining funds allocated to local transit and leisure.',
  },
];

export const INITIAL_GOALS: SavingsGoal[] = [
  {
    id: 'g-emergency',
    name: 'Emergency Fund',
    targetAmount: 100000,
    currentAmount: 0,
    targetDate: '2027-05-31',
    priority: 'high',
    linkedAccountId: 'acc-icici-savings',
    monthlyContributionTarget: 6500,
    notes: '6 months of mandatory living commitments reserve.',
    status: 'active',
    icon: 'ShieldCheck',
    category: 'Safety',
  },
  {
    id: 'g-macbook',
    name: 'New MacBook Pro M4',
    targetAmount: 150000,
    currentAmount: 0,
    targetDate: '2027-03-31',
    priority: 'high',
    linkedAccountId: 'acc-hdfc-salary',
    monthlyContributionTarget: 13000,
    notes: 'Workstation upgrade for productivity & development.',
    status: 'active',
    icon: 'Laptop',
    category: 'Gadget',
  },
  {
    id: 'g-london',
    name: 'London Summer Trip',
    targetAmount: 200000,
    currentAmount: 0,
    targetDate: '2027-08-31',
    priority: 'medium',
    linkedAccountId: 'acc-icici-savings',
    monthlyContributionTarget: 14000,
    notes: 'Flights, accommodations, and city tours.',
    status: 'active',
    icon: 'Plane',
    category: 'Vacation',
  },
  {
    id: 'g-investment',
    name: 'Business Investment Pool',
    targetAmount: 300000,
    currentAmount: 0,
    targetDate: '2027-12-31',
    priority: 'medium',
    linkedAccountId: 'acc-hdfc-salary',
    monthlyContributionTarget: 17500,
    notes: 'Private equity seed capital for commercial venture.',
    status: 'active',
    icon: 'Briefcase',
    category: 'Wealth',
  },
];

export const DEMO_GOALS: SavingsGoal[] = [
  {
    id: 'g-emergency',
    name: 'Emergency Fund',
    targetAmount: 100000,
    currentAmount: 48000,
    targetDate: '2027-05-31',
    priority: 'high',
    linkedAccountId: 'acc-icici-savings',
    monthlyContributionTarget: 6500,
    notes: '6 months of mandatory living commitments reserve.',
    status: 'active',
    icon: 'ShieldCheck',
    category: 'Safety',
  },
  {
    id: 'g-macbook',
    name: 'New MacBook Pro M4',
    targetAmount: 150000,
    currentAmount: 72000,
    targetDate: '2027-03-31',
    priority: 'high',
    linkedAccountId: 'acc-hdfc-salary',
    monthlyContributionTarget: 13000,
    notes: 'Workstation upgrade for productivity & development.',
    status: 'active',
    icon: 'Laptop',
    category: 'Gadget',
  },
  {
    id: 'g-london',
    name: 'London Summer Trip',
    targetAmount: 200000,
    currentAmount: 45000,
    targetDate: '2027-08-31',
    priority: 'medium',
    linkedAccountId: 'acc-icici-savings',
    monthlyContributionTarget: 14000,
    notes: 'Flights, accommodations, and city tours.',
    status: 'active',
    icon: 'Plane',
    category: 'Vacation',
  },
  {
    id: 'g-investment',
    name: 'Business Investment Pool',
    targetAmount: 300000,
    currentAmount: 35000,
    targetDate: '2027-12-31',
    priority: 'medium',
    linkedAccountId: 'acc-hdfc-salary',
    monthlyContributionTarget: 17500,
    notes: 'Private equity seed capital for commercial venture.',
    status: 'active',
    icon: 'Briefcase',
    category: 'Wealth',
  },
];

export const INITIAL_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-netflix',
    name: 'Netflix 4K Ultra HD',
    cost: 649,
    frequency: 'monthly',
    renewalDate: '2026-09-28',
    accountId: 'acc-regalia-card',
    category: 'Entertainment',
    isActive: true,
    reminderDaysBefore: 3,
    lastUsedDate: '2026-09-20',
  },
  {
    id: 'sub-spotify',
    name: 'Spotify Premium Individual',
    cost: 119,
    frequency: 'monthly',
    renewalDate: '2026-09-25',
    accountId: 'acc-upi-wallet',
    category: 'Entertainment',
    isActive: true,
    reminderDaysBefore: 2,
    lastUsedDate: '2026-09-21',
  },
  {
    id: 'sub-gym',
    name: 'Gold’s Fitness & Spa',
    cost: 2500,
    frequency: 'monthly',
    renewalDate: '2026-10-01',
    accountId: 'acc-hdfc-salary',
    category: 'Health',
    isActive: true,
    reminderDaysBefore: 5,
    lastUsedDate: '2026-08-14', // Flagged by AI Coach as low usage!
    notes: 'Low attendance detected last month (only 2 check-ins).',
  },
  {
    id: 'sub-prime',
    name: 'Amazon Prime Annual',
    cost: 1499,
    frequency: 'yearly',
    renewalDate: '2026-11-15',
    accountId: 'acc-regalia-card',
    category: 'Shopping',
    isActive: true,
    reminderDaysBefore: 7,
  },
  {
    id: 'sub-claude',
    name: 'AI Assistant Pro Suite',
    cost: 1999,
    frequency: 'monthly',
    renewalDate: '2026-10-05',
    accountId: 'acc-regalia-card',
    category: 'Education',
    isActive: true,
    reminderDaysBefore: 2,
    lastUsedDate: '2026-09-22',
  },
  {
    id: 'sub-icloud',
    name: 'iCloud+ 200GB Storage',
    cost: 219,
    frequency: 'monthly',
    renewalDate: '2026-10-12',
    accountId: 'acc-regalia-card',
    category: 'Bills & Utilities',
    isActive: true,
    reminderDaysBefore: 2,
  },
];

export const INITIAL_RECURRING_RULES: RecurringRule[] = [
  {
    id: 'rec-salary',
    name: 'Monthly Corporate Salary',
    type: 'income',
    amount: 75000,
    frequency: 'monthly',
    nextOccurrence: '2026-10-01',
    accountId: 'acc-hdfc-salary',
    category: 'Salary',
    autoCreate: true,
    reminderDaysBefore: 1,
    status: 'active',
  },
  {
    id: 'rec-rent',
    name: 'Apartment Lease Rent',
    type: 'expense',
    amount: 22000,
    frequency: 'monthly',
    nextOccurrence: '2026-10-05',
    accountId: 'acc-hdfc-salary',
    category: 'Rent & Housing',
    autoCreate: false, // Reminder only per user choice
    reminderDaysBefore: 3,
    status: 'active',
  },
  {
    id: 'rec-fiber',
    name: 'Airtel Broadband Fiber',
    type: 'expense',
    amount: 1180,
    frequency: 'monthly',
    nextOccurrence: '2026-09-27',
    accountId: 'acc-upi-wallet',
    category: 'Bills & Utilities',
    autoCreate: false,
    reminderDaysBefore: 3,
    status: 'active',
  },
  {
    id: 'rec-car-emi',
    name: 'HDFC Vehicle Loan EMI',
    type: 'expense',
    amount: 14200,
    frequency: 'monthly',
    nextOccurrence: '2026-10-10',
    accountId: 'acc-hdfc-salary',
    category: 'Transport',
    autoCreate: true,
    reminderDaysBefore: 2,
    status: 'active',
  },
];

export const INITIAL_NOTIFICATIONS: SmartNotification[] = [
  {
    id: 'notif-welcome',
    title: 'Finance Tracker Ready',
    message: 'All account balances and numbers are reset to ₹0. Tap + to record your first income, expense, or transfer.',
    type: 'insight',
    isRead: false,
    actionScreen: 'dashboard',
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_NOTIFICATIONS: SmartNotification[] = [
  {
    id: 'notif-1',
    title: 'Food Spending Alert',
    message: 'Your food spending is 24% higher than your recent average.',
    type: 'alert',
    isRead: false,
    actionScreen: 'budgets',
    createdAt: '2026-09-22T08:30:00Z',
  },
  {
    id: 'notif-2',
    title: 'Electricity Bill Upcoming',
    message: 'Your Tata Power electricity bill of ₹2,100 is due in 3 days.',
    type: 'reminder',
    isRead: false,
    actionScreen: 'bills',
    createdAt: '2026-09-22T06:00:00Z',
  },
  {
    id: 'notif-3',
    title: 'Monthly Spending Runway',
    message: 'You have ₹8,500 remaining for this month’s planned discretionary spending.',
    type: 'insight',
    isRead: false,
    actionScreen: 'ai_coach',
    createdAt: '2026-09-21T18:00:00Z',
  },
  {
    id: 'notif-4',
    title: 'Savings Goal Pacing',
    message: 'Emergency Fund contribution is ₹3,500 below this month’s pace. Consider topping up from surplus.',
    type: 'alert',
    isRead: true,
    actionScreen: 'goals',
    createdAt: '2026-09-20T12:00:00Z',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [];

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    amount: 75000,
    currency: 'INR',
    accountId: 'acc-hdfc-salary',
    category: 'Salary',
    date: '2026-09-01',
    notes: 'September 2026 Primary Corporate Salary',
    tags: ['Payroll', 'Corporate'],
    createdAt: '2026-09-01T09:00:00Z',
  },
  {
    id: 'tx-2',
    type: 'expense',
    amount: 22000,
    currency: 'INR',
    accountId: 'acc-hdfc-salary',
    category: 'Rent & Housing',
    subcategory: 'Apartment Rent',
    date: '2026-09-05',
    notes: 'September Apartment Rent via RTGS',
    tags: ['Fixed', 'Housing'],
    createdAt: '2026-09-05T10:30:00Z',
  },
  {
    id: 'tx-3',
    type: 'expense',
    amount: 14200,
    currency: 'INR',
    accountId: 'acc-hdfc-salary',
    category: 'Transport',
    subcategory: 'Car Loan EMI',
    date: '2026-09-10',
    notes: 'Monthly Auto Debit Vehicle Loan EMI',
    tags: ['EMI', 'Debt'],
    isAutoPosted: true,
    createdAt: '2026-09-10T04:00:00Z',
  },
  {
    id: 'tx-4',
    type: 'transfer', // Critical accounting rule: does NOT touch income or expense!
    amount: 10000,
    currency: 'INR',
    accountId: 'acc-hdfc-salary',
    toAccountId: 'acc-icici-savings',
    category: 'Transfer',
    date: '2026-09-02',
    notes: 'Transfer to Emergency Savings',
    tags: ['Self-Transfer', 'Savings'],
    createdAt: '2026-09-02T11:00:00Z',
  },
  {
    id: 'tx-5',
    type: 'expense',
    amount: 4500,
    currency: 'INR',
    accountId: 'acc-regalia-card',
    category: 'Shopping',
    subcategory: 'Clothing',
    date: '2026-09-12',
    notes: 'Zara Festive Wardrobe & Blazer',
    tags: ['Festive', 'Discretionary'],
    createdAt: '2026-09-12T16:20:00Z',
  },
  {
    id: 'tx-6',
    type: 'expense',
    amount: 1850,
    currency: 'INR',
    accountId: 'acc-upi-wallet',
    category: 'Food & Dining',
    subcategory: 'Restaurants',
    date: '2026-09-15',
    notes: 'Artisan Bistro Dinner with Team',
    tags: ['Dining', 'Social'],
    createdAt: '2026-09-15T21:40:00Z',
  },
  {
    id: 'tx-7',
    type: 'expense',
    amount: 720,
    currency: 'INR',
    accountId: 'acc-cash-wallet',
    category: 'Food & Dining',
    subcategory: 'Groceries',
    date: '2026-09-16',
    notes: 'Organic Farmer Market produce',
    tags: ['Cash', 'Groceries'],
    createdAt: '2026-09-16T08:15:00Z',
  },
  {
    id: 'tx-8',
    type: 'expense',
    amount: 630,
    currency: 'INR',
    accountId: 'acc-upi-wallet',
    category: 'Food & Dining',
    subcategory: 'Food Delivery',
    date: '2026-09-18',
    notes: 'Swiggy Gourmet Dinner box',
    tags: ['Delivery'],
    createdAt: '2026-09-18T20:10:00Z',
  },
  {
    id: 'tx-9',
    type: 'expense',
    amount: 250,
    currency: 'INR',
    accountId: 'acc-cash-wallet',
    category: 'Food & Dining',
    subcategory: 'Lunch',
    date: '2026-09-19',
    notes: 'Executive Lunch Bowl (Voice Entry Test)',
    tags: ['Voice', 'Lunch'],
    createdAt: '2026-09-19T13:00:00Z',
  },
  {
    id: 'tx-10',
    type: 'credit_card_payment', // Liability settlement: transfer from bank to credit card
    amount: 12000,
    currency: 'INR',
    accountId: 'acc-hdfc-salary',
    toAccountId: 'acc-regalia-card',
    category: 'Credit Card Payment',
    date: '2026-09-06',
    notes: 'Previous Month Regalia Gold Statement Settlement',
    tags: ['CreditCardSettlement'],
    createdAt: '2026-09-06T15:00:00Z',
  },
  {
    id: 'tx-11',
    type: 'expense',
    amount: 1180,
    currency: 'INR',
    accountId: 'acc-upi-wallet',
    category: 'Bills & Utilities',
    subcategory: 'Broadband',
    date: '2026-09-07',
    notes: 'Airtel Fiber 300Mbps bill',
    tags: ['Utilities', 'WorkFromHome'],
    createdAt: '2026-09-07T12:00:00Z',
  },
  {
    id: 'tx-12',
    type: 'expense',
    amount: 3620,
    currency: 'INR',
    accountId: 'acc-regalia-card',
    category: 'Bills & Utilities',
    subcategory: 'Electricity',
    date: '2026-09-08',
    notes: 'Tata Power Smart Meter Bill',
    tags: ['Utilities'],
    createdAt: '2026-09-08T14:20:00Z',
  },
  {
    id: 'tx-13',
    type: 'expense',
    amount: 2200,
    currency: 'INR',
    accountId: 'acc-regalia-card',
    category: 'Transport',
    subcategory: 'Fuel',
    date: '2026-09-14',
    notes: 'Shell V-Power Premium Fuel',
    tags: ['Fuel'],
    createdAt: '2026-09-14T17:45:00Z',
  },
  {
    id: 'tx-14',
    type: 'expense',
    amount: 1400,
    currency: 'INR',
    accountId: 'acc-upi-wallet',
    category: 'Entertainment',
    subcategory: 'Movies',
    date: '2026-09-20',
    notes: 'PVR Director’s Cut IMAX Tickets',
    tags: ['Weekend'],
    createdAt: '2026-09-20T19:30:00Z',
  }
];
